#!/bin/bash (shebang)

#This will copy a file, appending the date and time to the end of the file name.

date_formatted=$(date +%m_%d_%y-%H.%M.%S)

echo "Current Date and Time: " $date_formatted

cp -iv $1 $2.$date_formatted
